//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExpress.Web.Demos.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevExpress.Web.Demos.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #region Copyright (c) 2000-2020 Developer Express Inc.
        ////*
        ///{*******************************************************************}
        ///{                                                                   }
        ///{       Developer Express .NET Component Library                    }
        ///{                                                                   }
        ///{                                                                   }
        ///{       Copyright (c) 2000-2020 Developer Express Inc.              }
        ///{       ALL RIGHTS RESERVE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Code_DirectoryManagmentUtils_cs {
            get {
                return ResourceManager.GetString("Code_DirectoryManagmentUtils_cs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #region Copyright (c) 2000-2020 Developer Express Inc.
        ////*
        ///{*******************************************************************}
        ///{                                                                   }
        ///{       Developer Express .NET Component Library                    }
        ///{                                                                   }
        ///{                                                                   }
        ///{       Copyright (c) 2000-2020 Developer Express Inc.              }
        ///{       ALL RIGHTS RESERVE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Code_RichEditDemoUtils_cs {
            get {
                return ResourceManager.GetString("Code_RichEditDemoUtils_cs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #region Copyright (c) 2000-2020 Developer Express Inc.
        ////*
        ///{*******************************************************************}
        ///{                                                                   }
        ///{       Developer Express .NET Component Library                    }
        ///{                                                                   }
        ///{                                                                   }
        ///{       Copyright (c) 2000-2020 Developer Express Inc.              }
        ///{       ALL RIGHTS RESERVE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataProvider_Arts_cs {
            get {
                return ResourceManager.GetString("DataProvider_Arts_cs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #region Copyright (c) 2000-2020 Developer Express Inc.
        ////*
        ///{*******************************************************************}
        ///{                                                                   }
        ///{       Developer Express .NET Component Library                    }
        ///{                                                                   }
        ///{                                                                   }
        ///{       Copyright (c) 2000-2020 Developer Express Inc.              }
        ///{       ALL RIGHTS RESERVE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataProvider_HeadphonesModel_cs {
            get {
                return ResourceManager.GetString("DataProvider_HeadphonesModel_cs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #region Copyright (c) 2000-2020 Developer Express Inc.
        ////*
        ///{*******************************************************************}
        ///{                                                                   }
        ///{       Developer Express .NET Component Library                    }
        ///{                                                                   }
        ///{                                                                   }
        ///{       Copyright (c) 2000-2020 Developer Express Inc.              }
        ///{       ALL RIGHTS RESERVE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataProvider_Homes_cs {
            get {
                return ResourceManager.GetString("DataProvider_Homes_cs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #region Copyright (c) 2000-2020 Developer Express Inc.
        ////*
        ///{*******************************************************************}
        ///{                                                                   }
        ///{       Developer Express .NET Component Library                    }
        ///{                                                                   }
        ///{                                                                   }
        ///{       Copyright (c) 2000-2020 Developer Express Inc.              }
        ///{       ALL RIGHTS RESERVE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataProvider_LargeDatabase_cs {
            get {
                return ResourceManager.GetString("DataProvider_LargeDatabase_cs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #region Copyright (c) 2000-2020 Developer Express Inc.
        ////*
        ///{*******************************************************************}
        ///{                                                                   }
        ///{       Developer Express .NET Component Library                    }
        ///{                                                                   }
        ///{                                                                   }
        ///{       Copyright (c) 2000-2020 Developer Express Inc.              }
        ///{       ALL RIGHTS RESERVE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataProvider_Northwind_cs {
            get {
                return ResourceManager.GetString("DataProvider_Northwind_cs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #region Copyright (c) 2000-2020 Developer Express Inc.
        ////*
        ///{*******************************************************************}
        ///{                                                                   }
        ///{       Developer Express .NET Component Library                    }
        ///{                                                                   }
        ///{                                                                   }
        ///{       Copyright (c) 2000-2020 Developer Express Inc.              }
        ///{       ALL RIGHTS RESERVE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataProvider_WorldCities_cs {
            get {
                return ResourceManager.GetString("DataProvider_WorldCities_cs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4NCjwhLS0gR2VuZXJhdG9yOiBBZG9iZSBJbGx1c3RyYXRvciAyMS4xLjAsIFNWRyBFeHBvcnQgUGx1Zy1JbiAuIFNWRyBWZXJzaW9uOiA2LjAwIEJ1aWxkIDApICAtLT4NCjxzdmcgdmVyc2lvbj0iMS4xIiBpZD0i0KHQu9C+0LlfMSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayIgeD0iMHB4IiB5PSIwcHgiDQoJIHZpZXdCb3g9IjAgMCAxNiAxNiIgc3R5bGU9ImVuYWJsZS1iYWNrZ3JvdW5kOm5ldyAwIDAgMTYgMTY7IiB4bWw6c3BhY2U9InByZXNlcnZlIj4NCjxzdHlsZSB0eXBlPS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IconDataUri1200x800 {
            get {
                return ResourceManager.GetString("IconDataUri1200x800", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4NCjwhLS0gR2VuZXJhdG9yOiBBZG9iZSBJbGx1c3RyYXRvciAyMS4xLjAsIFNWRyBFeHBvcnQgUGx1Zy1JbiAuIFNWRyBWZXJzaW9uOiA2LjAwIEJ1aWxkIDApICAtLT4NCjxzdmcgdmVyc2lvbj0iMS4xIiBpZD0i0KHQu9C+0LlfMSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayIgeD0iMHB4IiB5PSIwcHgiDQoJIHZpZXdCb3g9IjAgMCAxNiAxNiIgc3R5bGU9ImVuYWJsZS1iYWNrZ3JvdW5kOm5ldyAwIDAgMTYgMTY7IiB4bWw6c3BhY2U9InByZXNlcnZlIj4NCjxzdHlsZSB0eXBlPS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IconDataUri576x768 {
            get {
                return ResourceManager.GetString("IconDataUri576x768", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4NCjwhLS0gR2VuZXJhdG9yOiBBZG9iZSBJbGx1c3RyYXRvciAyMS4xLjAsIFNWRyBFeHBvcnQgUGx1Zy1JbiAuIFNWRyBWZXJzaW9uOiA2LjAwIEJ1aWxkIDApICAtLT4NCjxzdmcgdmVyc2lvbj0iMS4xIiBpZD0i0KHQu9C+0LlfMSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayIgeD0iMHB4IiB5PSIwcHgiDQoJIHZpZXdCb3g9IjAgMCAxNiAxNiIgc3R5bGU9ImVuYWJsZS1iYWNrZ3JvdW5kOm5ldyAwIDAgMTYgMTY7IiB4bWw6c3BhY2U9InByZXNlcnZlIj4NCjxzdHlsZSB0eXBlPS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IconDataUri768x576 {
            get {
                return ResourceManager.GetString("IconDataUri768x576", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4NCjwhLS0gR2VuZXJhdG9yOiBBZG9iZSBJbGx1c3RyYXRvciAyMS4xLjAsIFNWRyBFeHBvcnQgUGx1Zy1JbiAuIFNWRyBWZXJzaW9uOiA2LjAwIEJ1aWxkIDApICAtLT4NCjxzdmcgdmVyc2lvbj0iMS4xIiBpZD0i0KHQu9C+0LlfMSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayIgeD0iMHB4IiB5PSIwcHgiDQoJIHZpZXdCb3g9IjAgMCAxNiAxNiIgc3R5bGU9ImVuYWJsZS1iYWNrZ3JvdW5kOm5ldyAwIDAgMTYgMTY7IiB4bWw6c3BhY2U9InByZXNlcnZlIj4NCjxzdHlsZSB0eXBlPS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IconDataUri800x1200 {
            get {
                return ResourceManager.GetString("IconDataUri800x1200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4NCjwhLS0gR2VuZXJhdG9yOiBBZG9iZSBJbGx1c3RyYXRvciAyMS4xLjAsIFNWRyBFeHBvcnQgUGx1Zy1JbiAuIFNWRyBWZXJzaW9uOiA2LjAwIEJ1aWxkIDApICAtLT4NCjxzdmcgdmVyc2lvbj0iMS4xIiBpZD0i0KHQu9C+0LlfMSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayIgeD0iMHB4IiB5PSIwcHgiDQoJIHZpZXdCb3g9IjAgMCAxNiAxNiIgc3R5bGU9ImVuYWJsZS1iYWNrZ3JvdW5kOm5ldyAwIDAgMTYgMTY7IiB4bWw6c3BhY2U9InByZXNlcnZlIj4NCjxzdHlsZSB0eXBlPS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IconDataUriFullscreen {
            get {
                return ResourceManager.GetString("IconDataUriFullscreen", resourceCulture);
            }
        }
    }
}
