using FluentValidation;
using Ninject.Modules;
using Bps.BpsBase.Entities.Concrete;
using Bps.BpsBase.Business.ValidationRules.FluentValidation;
using Bps.BpsBase.Entities.Concrete.CM;
using Bps.BpsBase.Business.ValidationRules.FluentValidation.CM;
using Bps.BpsBase.Entities.Concrete.CR;
using Bps.BpsBase.Business.ValidationRules.FluentValidation.CR;
using Bps.BpsBase.Entities.Concrete.FY;
using Bps.BpsBase.Business.ValidationRules.FluentValidation.FY;
using Bps.BpsBase.Entities.Concrete.GN;
using Bps.BpsBase.Business.ValidationRules.FluentValidation.GN;
using Bps.BpsBase.Entities.Concrete.IK;
using Bps.BpsBase.Business.ValidationRules.FluentValidation.IK;
using Bps.BpsBase.Entities.Concrete.IS;
using Bps.BpsBase.Business.ValidationRules.FluentValidation.IS;
using Bps.BpsBase.Entities.Concrete.KS;
using Bps.BpsBase.Business.ValidationRules.FluentValidation.KS;
using Bps.BpsBase.Entities.Concrete.MH;
using Bps.BpsBase.Business.ValidationRules.FluentValidation.MH;
using Bps.BpsBase.Entities.Concrete.SA;
using Bps.BpsBase.Business.ValidationRules.FluentValidation.SA;
using Bps.BpsBase.Entities.Concrete.SH;
using Bps.BpsBase.Business.ValidationRules.FluentValidation.SH;
using Bps.BpsBase.Entities.Concrete.SN;
using Bps.BpsBase.Business.ValidationRules.FluentValidation.SN;
using Bps.BpsBase.Entities.Concrete.SP;
using Bps.BpsBase.Business.ValidationRules.FluentValidation.SP;
using Bps.BpsBase.Entities.Concrete.ST;
using Bps.BpsBase.Business.ValidationRules.FluentValidation.ST;
using Bps.BpsBase.Entities.Concrete.TS;
using Bps.BpsBase.Business.ValidationRules.FluentValidation.TS;
using Bps.BpsBase.Entities.Concrete.UA;
using Bps.BpsBase.Business.ValidationRules.FluentValidation.UA;
using Bps.BpsBase.Entities.Concrete.UR;
using Bps.BpsBase.Business.ValidationRules.FluentValidation.UR;
using Bps.BpsBase.Entities.Concrete.WM;
using Bps.BpsBase.Business.ValidationRules.FluentValidation.WM;

namespace Bps.BpsBase.Business.DependencyResolvers.Ninject
{
    public class ValidationModule:NinjectModule
    {
        public override void Load()
        {
            Bind<IValidator<CMAKSN>>().To<CmaksnValidator>().InSingletonScope();
            Bind<IValidator<CMKART>>().To<CmkartValidator>().InSingletonScope();
            Bind<IValidator<CRADRS>>().To<CradrsValidator>().InSingletonScope();
            Bind<IValidator<CRBANK>>().To<CrbankValidator>().InSingletonScope();
            Bind<IValidator<CRCAFY>>().To<CrcafyValidator>().InSingletonScope();
            Bind<IValidator<CRCARI>>().To<CrcariValidator>().InSingletonScope();
            Bind<IValidator<CRYTKL>>().To<CrytklValidator>().InSingletonScope();
            Bind<IValidator<DOVKUR>>().To<DovkurValidator>().InSingletonScope();
            Bind<IValidator<FYShopifyImage>>().To<FyshopifyimageValidator>().InSingletonScope();
            Bind<IValidator<FYShopifyOption>>().To<FyshopifyoptionValidator>().InSingletonScope();
            Bind<IValidator<FYShopifyOrder>>().To<FyshopifyorderValidator>().InSingletonScope();
            Bind<IValidator<FYShopifyProduct>>().To<FyshopifyproductValidator>().InSingletonScope();
            Bind<IValidator<FYShopifyVariant>>().To<FyshopifyvariantValidator>().InSingletonScope();
            Bind<IValidator<GNBNHR>>().To<GnbnhrValidator>().InSingletonScope();
            Bind<IValidator<GNDPNO>>().To<GndpnoValidator>().InSingletonScope();
            Bind<IValidator<GNDPTN>>().To<GndptnValidator>().InSingletonScope();
            Bind<IValidator<GNDPTP>>().To<GndptpValidator>().InSingletonScope();
            Bind<IValidator<GNDPZM>>().To<GndpzmValidator>().InSingletonScope();
            Bind<IValidator<GNEVRK>>().To<GnevrkValidator>().InSingletonScope();
            Bind<IValidator<GNFILE>>().To<GnfileValidator>().InSingletonScope();
            Bind<IValidator<GNKLOP>>().To<GnklopValidator>().InSingletonScope();
            Bind<IValidator<GNKOSL>>().To<GnkoslValidator>().InSingletonScope();
            Bind<IValidator<GNKUKR>>().To<GnkukrValidator>().InSingletonScope();
            Bind<IValidator<GNKULL>>().To<GnkullValidator>().InSingletonScope();
            Bind<IValidator<GNKXML>>().To<GnkxmlValidator>().InSingletonScope();
            Bind<IValidator<GNLKHR>>().To<GnlkhrValidator>().InSingletonScope();
            Bind<IValidator<GNMENU>>().To<GnmenuValidator>().InSingletonScope();
            Bind<IValidator<GNMESJ>>().To<GnmesjValidator>().InSingletonScope();
            Bind<IValidator<GNOPHR>>().To<GnophrValidator>().InSingletonScope();
            Bind<IValidator<GNOPTP>>().To<GnoptpValidator>().InSingletonScope();
            Bind<IValidator<GNORGA>>().To<GnorgaValidator>().InSingletonScope();
            Bind<IValidator<GNORHR>>().To<GnorhrValidator>().InSingletonScope();
            Bind<IValidator<GNTHRK>>().To<GnthrkValidator>().InSingletonScope();
            Bind<IValidator<GNTIPI>>().To<GntipiValidator>().InSingletonScope();
            Bind<IValidator<GNYETB>>().To<GnyetbValidator>().InSingletonScope();
            Bind<IValidator<GNYETK>>().To<GnyetkValidator>().InSingletonScope();
            Bind<IValidator<IKPERS>>().To<IkpersValidator>().InSingletonScope();
            Bind<IValidator<ISPLAN>>().To<IsplanValidator>().InSingletonScope();
            Bind<IValidator<ISPLST>>().To<IsplstValidator>().InSingletonScope();
            Bind<IValidator<ISREVZ>>().To<IsrevzValidator>().InSingletonScope();
            Bind<IValidator<ISRVHR>>().To<IsrvhrValidator>().InSingletonScope();
            Bind<IValidator<ISURBG>>().To<IsurbgValidator>().InSingletonScope();
            Bind<IValidator<ISYROP>>().To<IsyropValidator>().InSingletonScope();
            Bind<IValidator<ISYRTN>>().To<IsyrtnValidator>().InSingletonScope();
            Bind<IValidator<KSKASA>>().To<KskasaValidator>().InSingletonScope();
            Bind<IValidator<LOCKED>>().To<LockedValidator>().InSingletonScope();
            Bind<IValidator<Logs>>().To<LogsValidator>().InSingletonScope();
            Bind<IValidator<MHHSPL>>().To<MhhsplValidator>().InSingletonScope();
            Bind<IValidator<SADEGA>>().To<SadegaValidator>().InSingletonScope();
            Bind<IValidator<SHSRVS>>().To<ShsrvsValidator>().InSingletonScope();
            Bind<IValidator<SIRKET>>().To<SirketValidator>().InSingletonScope();
            Bind<IValidator<SNIFBA>>().To<SnifbaValidator>().InSingletonScope();
            Bind<IValidator<SNKRTR>>().To<SnkrtrValidator>().InSingletonScope();
            Bind<IValidator<SNKRTY>>().To<SnkrtyValidator>().InSingletonScope();
            Bind<IValidator<SNSNKR>>().To<SnsnkrValidator>().InSingletonScope();
            Bind<IValidator<SNTYNN>>().To<SntynnValidator>().InSingletonScope();
            Bind<IValidator<SPDKDR>>().To<SpdkdrValidator>().InSingletonScope();
            Bind<IValidator<SPFBAS>>().To<SpfbasValidator>().InSingletonScope();
            Bind<IValidator<SPFHAR>>().To<SpfharValidator>().InSingletonScope();
            Bind<IValidator<SPFTIP>>().To<SpftipValidator>().InSingletonScope();
            Bind<IValidator<SPFTOP>>().To<SpftopValidator>().InSingletonScope();
            Bind<IValidator<SPKOSL>>().To<SpkoslValidator>().InSingletonScope();
            Bind<IValidator<SPODTB>>().To<SpodtbValidator>().InSingletonScope();
            Bind<IValidator<SPREZV>>().To<SprezvValidator>().InSingletonScope();
            Bind<IValidator<SPUROP>>().To<SpuropValidator>().InSingletonScope();
            Bind<IValidator<STBDRN>>().To<StbdrnValidator>().InSingletonScope();
            Bind<IValidator<STCRKD>>().To<StcrkdValidator>().InSingletonScope();
            Bind<IValidator<STDEPO>>().To<StdepoValidator>().InSingletonScope();
            Bind<IValidator<STDEPV>>().To<StdepvValidator>().InSingletonScope();
            Bind<IValidator<STDPYN>>().To<StdpynValidator>().InSingletonScope();
            Bind<IValidator<STFTIP>>().To<StftipValidator>().InSingletonScope();
            Bind<IValidator<STHBAS>>().To<SthbasValidator>().InSingletonScope();
            Bind<IValidator<STHRKT>>().To<SthrktValidator>().InSingletonScope();
            Bind<IValidator<STKART>>().To<StkartValidator>().InSingletonScope();
            Bind<IValidator<STKFIY>>().To<StkfiyValidator>().InSingletonScope();
            Bind<IValidator<STKFYT>>().To<StkfytValidator>().InSingletonScope();
            Bind<IValidator<STKMIH>>().To<StkmihValidator>().InSingletonScope();
            Bind<IValidator<STKMIZ>>().To<StkmizValidator>().InSingletonScope();
            Bind<IValidator<STMALT>>().To<StmaltValidator>().InSingletonScope();
            Bind<IValidator<STMHSB>>().To<StmhsbValidator>().InSingletonScope();
            Bind<IValidator<STNAME>>().To<StnameValidator>().InSingletonScope();
            Bind<IValidator<STOLCU>>().To<StolcuValidator>().InSingletonScope();
            Bind<IValidator<STOPTM>>().To<StoptmValidator>().InSingletonScope();
            Bind<IValidator<STSALE>>().To<StsaleValidator>().InSingletonScope();
            Bind<IValidator<STSERI>>().To<StseriValidator>().InSingletonScope();
            Bind<IValidator<STTDTR>>().To<SttdtrValidator>().InSingletonScope();
            Bind<IValidator<STUROP>>().To<SturopValidator>().InSingletonScope();
            Bind<IValidator<STURYR>>().To<SturyrValidator>().InSingletonScope();
            Bind<IValidator<STVMIH>>().To<StvmihValidator>().InSingletonScope();
            Bind<IValidator<STVMIZ>>().To<StvmizValidator>().InSingletonScope();
            Bind<IValidator<STVURY>>().To<StvuryValidator>().InSingletonScope();
            Bind<IValidator<TSFBAS>>().To<TsfbasValidator>().InSingletonScope();
            Bind<IValidator<TSFHAR>>().To<TsfharValidator>().InSingletonScope();
            Bind<IValidator<TSFTIP>>().To<TsftipValidator>().InSingletonScope();
            Bind<IValidator<UAKLTN>>().To<UakltnValidator>().InSingletonScope();
            Bind<IValidator<UAKLTP>>().To<UakltpValidator>().InSingletonScope();
            Bind<IValidator<UAMLTY>>().To<UamltyValidator>().InSingletonScope();
            Bind<IValidator<UASTBG>>().To<UastbgValidator>().InSingletonScope();
            Bind<IValidator<UASTRT>>().To<UastrtValidator>().InSingletonScope();
            Bind<IValidator<URAGAC>>().To<UragacValidator>().InSingletonScope();
            Bind<IValidator<URAGVR>>().To<UragvrValidator>().InSingletonScope();
            Bind<IValidator<URSURE>>().To<UrsureValidator>().InSingletonScope();
            Bind<IValidator<WMADRS>>().To<WmadrsValidator>().InSingletonScope();
            Bind<IValidator<WMADRT>>().To<WmadrtValidator>().InSingletonScope();
            Bind<IValidator<WMHRAT>>().To<WmhratValidator>().InSingletonScope();
            Bind<IValidator<WMHRKT>>().To<WmhrktValidator>().InSingletonScope();
            Bind<IValidator<WMNKSB>>().To<WmnksbValidator>().InSingletonScope();
        }
    }
}
