//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bps.BpsBase.WebUI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resourcesui {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resourcesui() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bps.BpsBase.WebUI.Resources.Resourcesui", typeof(Resourcesui).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beni Hatırla!.
        /// </summary>
        public static string beniHatirla {
            get {
                return ResourceManager.GetString("beniHatirla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil Seçiniz.
        /// </summary>
        public static string dilSeciniz {
            get {
                return ResourceManager.GetString("dilSeciniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evrak.
        /// </summary>
        public static string Evrak {
            get {
                return ResourceManager.GetString("Evrak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş.
        /// </summary>
        public static string giris {
            get {
                return ResourceManager.GetString("giris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoşgeldiniz.
        /// </summary>
        public static string hoşgeldiniz {
            get {
                return ResourceManager.GetString("hoşgeldiniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlemler.
        /// </summary>
        public static string İşlemler {
            get {
                return ResourceManager.GetString("İşlemler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Kodu giriniz....
        /// </summary>
        public static string kulkodgiriniz {
            get {
                return ResourceManager.GetString("kulkodgiriniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı.
        /// </summary>
        public static string Kullanıcı {
            get {
                return ResourceManager.GetString("Kullanıcı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Kodu.
        /// </summary>
        public static string kullaniciKod {
            get {
                return ResourceManager.GetString("kullaniciKod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen giriş yapınız..
        /// </summary>
        public static string lutfenGirisyapiniz {
            get {
                return ResourceManager.GetString("lutfenGirisyapiniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menü.
        /// </summary>
        public static string Menü {
            get {
                return ResourceManager.GetString("Menü", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesaj.
        /// </summary>
        public static string Mesaj {
            get {
                return ResourceManager.GetString("Mesaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popüler Diller.
        /// </summary>
        public static string populerDiller {
            get {
                return ResourceManager.GetString("populerDiller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        public static string sifre {
            get {
                return ResourceManager.GetString("sifre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifrenizi giriniz ....
        /// </summary>
        public static string sifreGiriniz {
            get {
                return ResourceManager.GetString("sifreGiriniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şiremi unuttum.
        /// </summary>
        public static string sifremiUnuttum {
            get {
                return ResourceManager.GetString("sifremiUnuttum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şirketler.
        /// </summary>
        public static string sirketler {
            get {
                return ResourceManager.GetString("sirketler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şirket Seçiniz.
        /// </summary>
        public static string sirketSeciniz {
            get {
                return ResourceManager.GetString("sirketSeciniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tanımlamalar.
        /// </summary>
        public static string Tanımlamalar {
            get {
                return ResourceManager.GetString("Tanımlamalar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip.
        /// </summary>
        public static string Tip {
            get {
                return ResourceManager.GetString("Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip Hareket.
        /// </summary>
        public static string Tip_Hareket {
            get {
                return ResourceManager.GetString("Tip Hareket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yetki.
        /// </summary>
        public static string Yetki {
            get {
                return ResourceManager.GetString("Yetki", resourceCulture);
            }
        }
    }
}
